### ISSUE TITLE
Extending pix2pix to Hyperspectral images

### ISSUE THREAD

**Issue by 1edv** [affinelayer/pix2pix-tensorflow#105]
Hi,

Any advice for someone hoping to extend pix2pix-tensorflow to images with more than three channels in the input/output images ( e.g. : hyperspectral images ) ?

Thanks !

**Comment by sam46** [comment]
Hello @1eesh  
I'm trying to do the same thing? 
Any luck or progress on your end?

**Comment by ZhuoerLyu** [comment]
Hi, are you guys stilling working on this topic. I am also interested in this. Can we talk about this?

**Comment by sam46** [comment]
@ZhuoerLyu I did write my own data loader, and had to do a couple edits to some other files as well.
This is my version of the repo, you can run a diff to see what I modified if you like:
https://github.com/sam46/capstone-weather/tree/master/pytorch-CycleGAN-and-pix2pix

**Comment by 1edv** [comment]
Hope this helps : https://github.com/phillipi/pix2pix/issues/128#issuecomment-391215427
