### ISSUE TITLE
Fixed 256x256 ?

### ISSUE THREAD

**Issue by kadarakos** [affinelayer/pix2pix-tensorflow#11]
How is it possible to use the model on different sized images e.g.: 480 x 640?

**Comment by christopherhesse** [comment]
I think it will work with those images by automatically resizing to 256x256.  You can fix the output aspect ratio with the `--aspect_ratio` option.  If you want to add layers to support, say, 512x512 as the input/output, that is possible but not supported by default.  I think you'd have to add two layers in the generator, 512x512=>256x256, and 256x256=>512x512, then add one in the discriminator, 512x512=>256x256.

**Comment by kadarakos** [comment]
And not square sizes like 480 x 640?

**Comment by christopherhesse** [comment]
That's not a square, and the model should work fine with that, it will just resize it internally.
