### ISSUE TITLE
Can i use multi core performance with tools/process.py ?

### ISSUE THREAD

**Issue by julien2512** [affinelayer/pix2pix-tensorflow#12]
Hi,

I am working on a model for edge-to-volcano (200 pics ready).
It would be great indeed if tools/process.py works on multi-core. May be I miss something ?

Regards,
Julien.

**Comment by christopherhesse** [comment]
You're probably looking for the `--workers` argument to process.py

**Comment by julien2512** [comment]
That's it ! Thank you.
