### ISSUE TITLE
【Help】: Tow input image and one output image, how to change code?

### ISSUE THREAD

**Issue by dustyYMelody7** [affinelayer/pix2pix-tensorflow#128]
Thanks for your code and work! 
When I use your code in my own work, I met a problem. My work is to input two images in the network, 

and then I want to recover one image from these two images above. 

How should I change the code to process this situation: two inputs and one output? I really want someone to help me. Thanks a lot!

**Comment by julien2512** [comment]
You need to play on inputs channels.
Have a look on
`def create_generator(generator_inputs, generator_outputs_channels):`
changes on channels dim affected by the conv layers
and
`def load_examples():`
where images are loaded.

Good luck !

**Comment by dustyYMelody7** [comment]
Thanks a lot! 
I will try it. 
May I ask you which country are you from? Could I communicate with you about this issue in detail?

**Comment by julien2512** [comment]
>  Could I communicate with you about this issue in detail?

Yes you can !

>  May I ask you which country are you from?

I don't speak english that bad ! :(

**Comment by dustyYMelody7** [comment]
I am from China. If you are the same as me, could I have your contact information to contact with you? Such as wechat or skype?

**Comment by julien2512** [comment]
@qihuaiyu What is the issue ?

**Comment by dustyYMelody7** [comment]
I have made it, but now I meet another problem, why the generator_loss_GAN increase all the time rather decrease during training?

**Comment by julien2512** [comment]
See #119
