### ISSUE TITLE
【help】why streaks on output pictures when I test the network?

### ISSUE THREAD

**Issue by dustyYMelody7** [affinelayer/pix2pix-tensorflow#132]
I trained the network on 18640 pictures,  and I change the pix2pix network into two inputs and one target, but when I try to check on my test sets, there are some streaks on my output pictures. Appreciate a lot if anyone knows the reason?

the pictures are shown below(from the left to right are input1,   input2,  output,  groundtruth):

**Comment by sunnyYaSky** [comment]
hi gay@qihuaiyu  have you change some parameters  or  just change the input ?

thx

**Comment by dustyYMelody7** [comment]
> hi gay@qihuaiyu have you change some parameters or just change the input ?
> 
> thx

I just change the input without changing parameters.
