### ISSUE TITLE
How do I utilize my exported model?

### ISSUE THREAD

**Issue by michaelkaesdorf** [affinelayer/pix2pix-tensorflow#137]
Hi :)
I trained my model, tested it and exported it.
I want to feed my model now with new input images. How do I do that?

Those are my exported files:
checkpoint
export.data-00000-of-00001
export.index
export.meta
options.json

What specific steps are required to make use of the exported model? It seems to me like I am missing a very obvious trivial thing but I just can't find it. As far as I understand, none of the pix2pix modes "train", "test" "export" are made for just processing input images.
In earlier versions there seemed to be the process-local.py; but as it has been removed, I guess there should be a better way to run it?

edit: ok well; I just produce my input images with a blank square on the right then.. it's a workaround but well.. 😄

**Comment by MuhammadAsadJaved** [comment]
Please read the last comment in this issue. @rosenbach 

https://github.com/affinelayer/pix2pix-tensorflow/issues/151
