### ISSUE TITLE
Multi GPU support?

### ISSUE THREAD

**Issue by tonmoyborah** [affinelayer/pix2pix-tensorflow#141]
Is there any way I can train this on multiple GPUs in parallel? Increasing batch size decreases training time significantly. Currently I can use a bs of 32 on a single GPU but I have another available (and listed in CUDA VISIBLE DEVICES). If I increase bs, the ResourceExhaustedError comes and I can monitor that only one GPU is used. Is there anyway I can use both? Thanks!
Regards

**Comment by julien2512** [comment]
You will need to add improvements to add multiple GPUs support.

Try that one :
https://jhui.github.io/2017/03/07/TensorFlow-GPU/

You need to follow "Data parallelism" on different "towers" (that mean different GPUs).
In such a model, variables should be attach to one CPU to be share between GPUs.

Good luck.
