### ISSUE TITLE
Dockerfile for tensorflow without gpu

### ISSUE THREAD

**Issue by julien2512** [affinelayer/pix2pix-tensorflow#15]
The branch "nogpu" from my pix2pix-tensorflow fork got a docker/Dockerfile which is able to run tensorflow without gpu :
https://github.com/julien2512/pix2pix-tensorflow/blob/nogpu/docker/Dockerfile

May it be a good idea to pull request it on your fork ? Tell me ;)

**Comment by christopherhesse** [comment]
In my experience, the gpu version of tensorflow runs fine without a gpu, is that not the case for you?

**Comment by julien2512** [comment]
Yes, it might work. There was too much error messages for me !
Indeed I will probably change my Dockerfile to use SSE4 instructions. Without GPU driver I will probably fail to do it.

I don't know either if there is a way to tell tensorflow not to use gpu drivers so that the error messages do not appear at each run.

Have you tryed the edge-2-volcano v1.1 ? http://163.172.41.53/ (intended for private use).
It's kind of fun !
;)

**Comment by christopherhesse** [comment]
Looks cool!  Those are just warnings on my machine, so I just ignore them.  Tensorflow seems a bit chatty no matter which version I use.

**Comment by julien2512** [comment]
Ok
