### ISSUE TITLE
pix2pix.py should work with newer versions of tensorfow than 1.0.0

### ISSUE THREAD

**Issue by clevinson** [affinelayer/pix2pix-tensorflow#17]
https://github.com/affinelayer/pix2pix-tensorflow/blob/master/pix2pix.py#L542-L543

Currently pix2pix only allows for Tensorflow version 1.0.0 and not more recent versions...

**Comment by robburke** [comment]
@clevinson I worked around this locally by modifying the constant in line 542 to 1.0.1 and it worked fine

**Comment by nonoesp** [comment]
Yes that works. I did the same and both training and testing work.

**Comment by christopherhesse** [comment]
This should be fixed now.
