### ISSUE TITLE
How To upload input image at web demo?

### ISSUE THREAD

**Issue by RuikangSun** [affinelayer/pix2pix-tensorflow#170]
Output image could be saved, however, input image can't be uploaded.
My model requires complex input. So how to upload image file as input?
I understand a little of Python, but nothing of JavaScript.
![afdasf](https://user-images.githubusercontent.com/20597187/62614139-67600380-b93d-11e9-8be7-23b5cb5c5708.png)

**Comment by RuikangSun** [comment]
Close old issues.

**Comment by QiyuanY** [comment]
Hello, did you solve the problem with uploading your images?

**Comment by RuikangSun** [comment]
> Hello, did you solve the problem with uploading your images?

并没有
