### ISSUE TITLE
Cloud ML Serving issue - input and filter must have the same depth: 1 vs 3

### ISSUE THREAD

**Issue by robburke** [affinelayer/pix2pix-tensorflow#18]
When following the instructions under "Cloud ML Serving" on [this page (server path)](https://github.com/affinelayer/pix2pix-tensorflow/tree/master/server), the upload-model.py call works, but the second command (call to process-cloud.py) fails. 

The response returned from request.execute()  is a key "error" with value:

`Prediction failed: Exception during model execution: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="input and filter must have the same depth: 1 vs 3 [[Node: generator/encoder_1/conv/Conv2D = Conv2D[T=DT_FLOAT, _output_shapes=[[1,128,128,64]], data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](generator/encoder_1/conv/Pad, generator/encoder_1/conv/filter/read)]]`

Wondering if anyone has insights what may be going wrong here.

**Comment by robburke** [comment]
Resolved: Was passing a grayscale image. Ensure images being passed to the service are PNGs with 3 channels.

**Comment by R-Miner** [comment]
passing a PNG with 3 channels did not help me. What else could be the reason? Any help appreciated!

**Comment by StormThorn91** [comment]
Hi R-Miner! Have you resolved your error already? Been experiencing the same error right now. :)
