### ISSUE TITLE
Discriminator's output shape

### ISSUE THREAD

**Issue by hwalsuklee** [affinelayer/pix2pix-tensorflow#21]
I'm looking into codes line by line.

I'm wondering why discriminator's output has a shape of [batch, 30, 30, 1].

The implemented discriminator seems to 70x70 discriminator in the original torch code.
For an input image of 256 x 256, I expected discriminator's output to be in the size of (256-70)x(256-70).
But it turns out to be 30x30.

Strangely, 1x1 discriminator in the original torch code also has an output in the size of 30x30.

Am I missing something?

Please answer me if there is anyone who knows about this.

**Comment by hwalsuklee** [comment]
I found author's answer in the original repository.

https://github.com/phillipi/pix2pix/issues/25

**Comment by programath** [comment]
hi hwalsuklee, I just don't understand why is 70x70 after reading the issue phillipi/pix2pix#25. the input_size =(output_size - 1)*stride+ksize. But I cannot get the result 70x70. Can you show me how to calculate it? thx.

**Comment by hwalsuklee** [comment]
@programath Hey. Sorry for late response. I just tried to run 'receptive_field_sizes.m' and got '70' as a receptive filed size. Please try `out = f(f(f(f(f(1, 4, 1), 4, 1), 4, 2), 4, 2), 4, 2);`

**Comment by emilwallner** [comment]
**Main misconception I had:** I thought that the first kernel or the input size was the same as the receptive field. So if the first kernel was 70 or the input image was 70x70, then the receptive field equals to 70. But it's calculated backwards from the final prediction. I outlined the calculations in python below to make it easier.

```python
def f(output_size, ksize, stride):
    return (output_size - 1) * stride + ksize

last_layer = f(output_size=1, ksize=4, stride=1)
# Receptive field: 4

fourth_layer = f(output_size=last_layer, ksize=4, stride=1)
# Receptive field: 7

third_layer = f(output_size=fourth_layer, ksize=4, stride=2)
# Receptive field: 16

second_layer = f(output_size=third_layer, ksize=4, stride=2)
# Receptive field: 34

first_layer = f(output_size=second_layer, ksize=4, stride=2)
# Receptive field: 70

print(first_layer)
```
