### ISSUE TITLE
Image does not have 3 channels

### ISSUE THREAD

**Issue by recursionbane** [affinelayer/pix2pix-tensorflow#26]
I have an color imageset as input, but I consistently trip this assertion:

    assertion = tf.assert_equal(tf.shape(raw_input)[2], 3, message="image does not have 3 channels")

The error I see is:

    tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [image does not have 3 channels]

Could you please elaborate on what the input image parameters are? Is having distinct R, G and B channel insufficient in an input JPEG? Is there a recommendation on post-processing JPEGs to fit the desired input image parameters?

These are the pertinent image properties as seen in IrfanView for my combined images:

- Compression: JPEG, quality: 75, subsampling ON (2x2)
- Resolution: 100 x 100 DPI
- Original size: 2393 x 655 (1.57 MPixels) 3.65
- Original colors: 16.7 Million (24 BitsPerPixel)
- Number of unique colors: 6108 (Auto counted)

Things I've tried:
- Using Latest commit d6f8e4c
- Resizing the input images to 512x256
- Converting the input images to PNG, also at 512x256

**Comment by recursionbane** [comment]
This seems to work when converted in IrfanView:

- Output: JPG - JPG/JPEG Format
- Options: Save quality: 95; ALL other checkboxes unchecked
- Advanced: Change color depth: 16.7 Million colors
- Advanced: Resize: 512x256 pixels, do not preserve aspect ratio

**Comment by m0ose** [comment]
I had that problem and fixed it by removing the alpha channel using skimage
```
from skimage import io
import os

def load_images_from_folder(folder):
    for filename in os.listdir(folder):
        f2 = os.path.join(folder,filename)
        img = io.imread(f2)
        img2 = img[:,:,:3]
        io.imsave(f2, img2)

load_images_from_folder('./blocksSynthetic/train')
```

**Comment by nooooonee** [comment]
I also encounter the same error,  and I fixed it by changing the code `raw_input = decode(contents)` into `raw_input = decode(contents, channels=3)` in function `load_examples()`.
