### ISSUE TITLE
Cache training data in memory to avoid disk latency

### ISSUE THREAD

**Issue by Cristy94** [affinelayer/pix2pix-tensorflow#31]
(I am new to ML and Tensorflow).

I am using Google ml-engine to train a network, the training data is stored in Google Cloud Storage. I might be wrong, but I noticed that the training inputs are not stored in RAM and read from the disk (in this from GFS) so I think this is a big bottleneck for training.

Can the current implementation be updated to have an option to store all training (input) data in memory at the start of the program and somehow avoid disk reads while training?

From what I read this could be solved by using tf queues or actually uploading the training data to the GPU and using it from there?

PS: Using the ml-engine tier BASIC_GPU, I get a training rate of about 5 images/sec. Shouldn't this be higher considering it's a (half of a) K80 GPU? I tried using a complex_model_m_gpu (which has 4 K80 GPUs) and a better CPU but it only increased to 5.1 images/sec.

PS2: I have managed to upload my training files to the ml-engine instance (so they are locally, on the same machine, not loaded from Google Cloud Storage) and the rate (for BASIC_GPU) went from 5 to 5.5 images/sec.

**Comment by Cristy94** [comment]
May be related: https://blog.metaflow.fr/tensorflow-how-to-optimise-your-input-pipeline-with-queues-and-multi-threading-e7c3874157e0

**Comment by mightydeveloper** [comment]
In current implementation, commit (d6f8e4ce00a1fd7a96a72ed17366bfcb207882c7),
in line 319 of pix2pix.py, it has 
`paths_batch, inputs_batch, targets_batch = tf.train.batch([paths, input_images, target_images], batch_size=a.batch_size)`
Internally in tensorflow, this tf.train.batch function uses the queuerunner and threads that your link mentions. So I don't think this is a big bottleneck. If you still think this is a bottleneck, you might want to increase the queue size or number of threads in tf.train.batch as a parameter. (default queue size is 32, and default number of threads is 1 as of API 1.1).
I think the slow training rate comes from the batch size which defaults to 1 in pix2pix.py
You might want to increase this number to train much faster, but this might not be the best method to train the model.

**Comment by Cristy94** [comment]
Yeah, I think the bottleneck is simply the GPU, but the images are not cached in memory while training because if I delete an image from the train folder while the training is underway it will throw an error because the image is not found, meaning that there are indeed file reads from the system while training.

With a batch size set to 3 on a K80 instance I get about 7 images/second. I don't really know if that's good or not but the training seems pretty slow.

**Comment by mightydeveloper** [comment]
TensorFlow's tf.train.batch does not cache the entire dataset in the memory. It caches just enough dataset so that the train takes efficiently and also does not consume unnecessary large amount of memory. It only caches up to the queue size.
In addition, every training data is used for each epoch. So if you delete the image, TensorFlow will not be able to run next epoch, because it will try to enqueue the data to the input queue.
