### ISSUE TITLE
'edges2cats' should be called 'feLines'

### ISSUE THREAD

**Issue by golanlevin** [affinelayer/pix2pix-tensorflow#5]
Suggestion by @dariusk

**Comment by dariusk** [comment]
Credit where credit is due, I merely quoted [Chris Millson](https://twitter.com/asameshimae/status/834375517923074049)!

**Comment by christopherhesse** [comment]
lawl

**Comment by akashdexati** [comment]
Hi
Do we have `edges2cats` dataset available ?

**Comment by MikeTheWatchGuy** [comment]
I too am looking for the data / instructions for `edges2cats`

I'm running on windows and managed to follow the complex steps to get the GPU version of `Tensorflow `running on my Windows 10 machine.  Even with a Core i9 processor and 64 GB of RAM, the GPU training run time put to shame the CPU .  It dropped from over 1 day to less than 4 hours.

Now that I've got the basic `Pix2Pix `running on my machine, I would love to train it using the `Edges2Cats `data.

My goal in this little project is to create a version that can be fed images directly.  The online demos all require you to draw, using a mouse, the image to process.  I think a version that takes JPGs or PNGs could produce wild effects if fed a line drawing of say one of us :-)  YOU, your face's features, with cat-meat hung from it.  THAT would be something to see!
Or, run a line drawing of your cat through it.  Cat to cat translation 👍 

Heck, I may even get it running on a website for everyone to enjoy if I can get some help here with the data.

Any help is
more than greatly appreciated
(pli ol multe estimita) in the [Esperanto language](https://en.wikipedia.org/wiki/Esperanto)

Thank you for your time.
