### ISSUE TITLE
How to set a suitable batch size to improve training time?

### ISSUE THREAD

**Issue by knaffe** [affinelayer/pix2pix-tensorflow#54]
I use my data to train the model. I have 30,000 samples. Now I am training my model on the TitanX, and it takes one epoch per hour with the default setting of batch size: 1. I guess it would take 200 hours in my case.
As a result, I want to set a larger batch size, but I don't have any experience in it. Need some help from you guys.
Thank you sooo much!

**Comment by imperative** [comment]
Batch size can be set as a command-line argument for this tool. See the beginning of the main source file for explanation of all command line arguments.
