### ISSUE TITLE
Process edges: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rainerkohlberger** [affinelayer/pix2pix-tensorflow#55]
Hi,
Getting the following error when trying to generate edges through process.py…
Pointed hard coded path to HED caffe version. What could be the problem? Thanks!

```
Traceback (most recent call last):
  File "tools/process.py", line 340, in <module>
    main()
  File "tools/process.py", line 304, in main
    process(src_path, dst_path)
  File "tools/process.py", line 233, in process
    dst = edges(src)
  File "tools/process.py", line 210, in edges
    subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by imperative** [comment]
You seem to operate on some modified version of the file process.py than what is in the repository? It's hard to know what is wrong if we can't see your code completely...
However in this case, I am guessing this is about line 183: https://github.com/affinelayer/pix2pix-tensorflow/blob/d6f8e4ce00a1fd7a96a72ed17366bfcb207882c7/tools/process.py#L183
Did you install Octave and all the needed plugins for it? 

Edges algorithm that is used in this code uses both Caffe and octave. First Caffe is run using a pretrained HED model, and then yet another small program written in Octave is run on the result of Caffe output.

**Comment by rainerkohlberger** [comment]
Thank you! That was it, Octave and packages weren't installed on my system.
