### ISSUE TITLE
What GPU are you using?

### ISSUE THREAD

**Issue by avloss** [affinelayer/pix2pix-tensorflow#6]
In your manual you mention:
(this may take 1-8 hours depending on GPU, on CPU you will be waiting for a bit)

May I ask what hardware is needed for this to finish within an hour? what hardware are you using? on a single `K80` from AWS it looks like it's going to take about 6 hours

**Comment by christopherhesse** [comment]
That seems reasonable.  I suspect the 9 hour estimate was based on a 1.3 TFLOPS Nvidia GTX 750 Ti.  I feel like the K80 should be like 4 hours, but it can depend on settings, etc.

**Comment by 983** [comment]
To have another data point, training on a 840M, which only has about 0.8 TFLOPS and a bandwidth of 16 GB/s as opposed to the 88 GB/s of the GTX 750 Ti, takes about 30 hours.
