### ISSUE TITLE
Continue training from a trained model on custom dataset

### ISSUE THREAD

**Issue by groot-1313** [affinelayer/pix2pix-tensorflow#76]
I have trained the network on custom dataset for a few epochs. But had to stop the training in the middle. How do I go about continuing the training from where I left off?
Thanks!

**Comment by julien2512** [comment]
There is a "--checkpoint" parameter on pix2pix.py tool. It starts from the last saving model operation.

**Comment by groot-1313** [comment]
Oh great! Thanks!
