### ISSUE TITLE
tfimage

### ISSUE THREAD

**Issue by heixi** [affinelayer/pix2pix-tensorflow#82]
hello, when i runing process.py, the error is no module named tfimage. i used tensorflow v0.12.1. Can you tell me your dependency library.

**Comment by heixi** [comment]
sorry, i know. thank you!

**Comment by ZhuoerLyu** [comment]
Hi, I got stuck at the same problem. How did you solve that problem? Could you please tell me how to solve that?

**Comment by JeremyJamesG** [comment]
Hey @heixi and @ZhuoerLyu  what was the issue with this? I have same problem. Thanks

**Comment by ZhuoerLyu** [comment]
Hi, I kind of forgot how I solved that, if I am right, it was a version issue. Remember to google the feedback and you can find the solution. This is basically how I solved it.

Good luck!

**Comment by JeremyJamesG** [comment]
THanks @ZhuoerLyu . I found the issue. For future reference - the tfimage module comes with this repo in the tools folder.

**Comment by ZhuoerLyu** [comment]
Cool! Thank you!
