### ISSUE TITLE
Can I specify the GPU id?

### ISSUE THREAD

**Issue by czxrrr** [affinelayer/pix2pix-tensorflow#9]
Hi!
I successfully run the code and get good result, but I am afraid the code is executed all by CPU
And I do have more than one GPUs on the machine.

May I ask How I can run the code with the help of GPU?

**Comment by christopherhesse** [comment]
You should use the tensorflow GPU version.  I don't have a multi GPU machine, but uou can specify CUDA_VISIBLE_DEVICES to set which GPU to use.
